apiVersion: crd.nsx.vmware.com/v1alpha1
kind: SecurityPolicy
metadata:
  name: vmapptier1-fw
  namespace: vmservice
spec:
  priority: 1
  appliedTo:
  - vmSelector:
      matchLabels:
        app: vmapptier1
  rules:
  - direction: in
    action: allow
    sources:
     - ipBlocks: 
       - cidr: 192.168.0.0/16
     - vmSelector:
         matchLabels:
           app: vmapptier1
     - podSelector:
         matchLabels:
           app: guestbook-ui
    ports:
     - protocol: TCP
       port: 80
  - direction : out
    action: allow
    destinations:
     - ipBlocks: 
       - cidr: 192.168.0.0/16
     - vmSelector:
         matchLabels:
           app: vmapptier1
     - podSelector:
         matchLabels:
           app: guestbook-ui
    ports:
     - protocol: UDP
       port: 53
  - name: "Pods/VMs to my PODS/VMS in "
    direction: in
    action: allow
    sources:
     - vmSelector:
         matchLabels:
           app: vmapptier1
     - podSelector:
         matchLabels:
           app: guestbook-ui
    ports:
     - protocol: TCP
       port: 80
       endPort: 443
  - name: "Pods/VMs to my PODS/VMS out"
    direction : out
    action: allow
    destinations:
     - vmSelector:
         matchLabels:
           app: vmapptier1
     - podSelector:
         matchLabels:
           app: guestbook-ui
    ports:
     - protocol: UDP
       port: 53
     - protocol: TCP
       port: 80
       endPort: 443

      