apiVersion: vmoperator.vmware.com/v1alpha4
kind: VirtualMachine
metadata:
  name: vmapptier1-1
  namespace: vmservice
  labels:
    app: vmapptier1
spec:
  imageName: vmi-4c48b6f40db2f6384
  className: best-effort-xsmall
  storageClass: home-mgmt-cl01-optimal-datastore-default-policy-raid5
  network:
  bootstrap:
    cloudInit:
      cloudConfig: {}
  network:
    interfaces:
      - name: eth0
        network:
          apiVersion: crd.nsx.vmware.com/v1alpha1
          kind: Subnet
          name: vmapptier1-subnet
